### ISSUE TITLE
IPython notebooks instead of trinket?

### ISSUE THREAD

**Issue by cdeil** [x-calibre/astropython#100]
The current "try python" is very limited and doesn't have a "wow" effect:
http://amanjhunjhunwala.pythonanywhere.com/try/python

Specifically this doesn't work:
```python
>>> import astropy
>>> import sherpa
>>> import my-favourite-astro-package-that's-mentioned-on-this-site-to-try-it-out
```

Maybe this site is the right location to get IPython notebooks with pre-loaded or easily accessible Python astro modules and example data for tutorials set up?
https://github.com/astropy/astropy-tutorials/issues/74
(I have some time next week and could help with setting up Docker images, but I don't know how to deploy docker containers in the cloud or integrate this into a site.)

**Comment by x-calibre** [comment]
I am fully aware how limited Trinket is , and that is the reason,it is reduced to a small text link on the bottom ! 
Before the project started , I wanted to have this embedded IPython notebook area , where users could try new packages on spot (it would be incredibly useful ).....but then it porting the old AstroPython site from Google Cloud and setting up a new one from scratch on another cloud in  less than 8 weeks , proved to be quite a heavy task , not allowing me to experiment further with the idea ! 
I have deployed IPython instances on EC2 clusters with Anaconda before and would love to experiment with it or even use Dockerized images for the purpose... But it is going to take quite some time (a month or two minimum before I can take it up) 

Any pull requests would be more than appreciated. The current application is running on a virtual Linux host on a EC2 server (managed by PythonAnywhere, to reduce maintenance and sysadmin load) !

**Comment by x-calibre** [comment]
Moving discussion to 
https://github.com/astropy/astropython.org/issues/7
