### ISSUE TITLE
populate script needs to be updated to work with unification

### ISSUE THREAD

**Issue by jeanconn** [x-calibre/astropython#11]
I can't seem to run populate.py at this point:

(astro)user@surfman ~/git/astropython/astropython $ python populate.py 
/opt/anaconda/envs/astro/lib/python2.7/site-packages/django/contrib/contenttypes/models.py:159: RemovedInDjango19Warning: Model class django.contrib.contenttypes.models.ContentType doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class ContentType(models.Model):

/opt/anaconda/envs/astro/lib/python2.7/site-packages/secretballot/__init__.py:8: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes import generic

/opt/anaconda/envs/astro/lib/python2.7/site-packages/haystack/utils/__init__.py:12: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils import importlib

Traceback (most recent call last):
  File "populate.py", line 15, in <module>
    from tutorials.models import Tutorial
ImportError: No module named tutorials.models

**Comment by x-calibre** [comment]
As I wrote in my Development note, this week I removed all the separate apps and just have one main app as a part of the unification.... the unification is almost complete .... things like the population script need to be suited to that..... @jeanconn ...The code should be check ready by Thursday (the Monday deadline was shifted to Friday as we had discussed in the email) 
Also, if it wouldnt be inconvenient, could you fork the repo again -there has been a major UI change which I have just uploaded and I would like to know , if the new UI is cleaner and better than the old one.

**Comment by jeanconn** [comment]
Great.  Thanks.  I saw in your notes that you were unifying, but it wasn't clear to me that the population script had not yet been updated to match.  No pressure from me; but also probably not bad to have an open github issue for it.  And yes, I've got your UI updates from today and will be looking that over.

**Comment by x-calibre** [comment]
Thanks for pointing them out :+1:

**Comment by x-calibre** [comment]
Fixed ! Population Script now working ! 
Note : All running the population script, we need to go to Django Admin Panel and approve all moderations from the DJANGO MODERATION tab .... adding it to the readme

**Comment by x-calibre** [comment]
Sorry you had that experience !
