### ISSUE TITLE
Landing page image issues

### ISSUE THREAD

**Issue by taldcroft** [x-calibre/astropython#112]
- [x] I don't see the credit or description anywhere.  Probably at the bottom of the image there should be a line with "Description Credit: ...." where Description is a link that does a little pop-up or hover-over with the description.
- [ ] It seems like there is an off-by-one problem with the image selection circles below
- [x] It doesn't seem to be picking the initial image randomly, I always get the satellite view of the Earth

**Comment by x-calibre** [comment]
The link to credit and description appeared on clicking the image itself....I guess that would be unclear , so I removed that and added a "About Slider Images" link at the footer !
Small bug in slider code that is causing both the shuffling and random selection.... will definitely fix it by tommorow

**Comment by x-calibre** [comment]
Done ! Sorry we had to encounter this !
