### ISSUE TITLE
Formal Testing !

### ISSUE THREAD

**Issue by x-calibre** [x-calibre/astropython#25]

**Comment by x-calibre** [comment]
Maybe later

**Comment by embray** [comment]
Sounds like a good idea to have at some point before long (although maybe time is short for GSoC purposes).  Have you worked much with functional web testing frameworks before (windmill, selenium, etc.)?

**Comment by x-calibre** [comment]
Thank you @embray for taking the time out for the feedback !
I have read a bit about Tox (Django Testing Framework) , Selenium ,etc and it would be fun to have a hands-on experience with it .. after GSoC, this will definately be on the priority list !

**Comment by embray** [comment]
FWIW tox isn't a Django testing framework (unless there's a different tox I haven't heard of).  It's not even a test framework at all--it's for automation of running tests for Python projects, in particular against multiple different interpeters.

**Comment by x-calibre** [comment]
Just goes to show my experience with Formal Testing then ! 
Ran a few django tests on tox - thought that is was a feature restricted to django !  Thank you for correcting me !
