### ISSUE TITLE
Issue warning when switching editor that content will be lost, or else disable switching

### ISSUE THREAD

**Issue by taldcroft** [x-calibre/astropython#38]
Even though there is a text warning below, when content will actually be lost due to switching editor then a confirmation dialog should come up.

An alternative is to simply disallow switching if there is any content entered.

**Comment by x-calibre** [comment]
![image](https://cloud.githubusercontent.com/assets/10886527/8374970/22020404-1c17-11e5-951e-b6ddfba7d64e.png)

Done ! This is a screenshot !

**Comment by taldcroft** [comment]
:+1:
