### ISSUE TITLE
Art can block homepage github login

### ISSUE THREAD

**Issue by jeanconn** [x-calibre/astropython#44]
The github link is not clickable at this screen width (not sure how to grab the actual width from this Mac Chrome browser, but you get the idea).

![screen shot 2015-07-09 at 11 35 10 am](https://cloud.githubusercontent.com/assets/791508/8600993/c21b6c02-262e-11e5-8b5d-4daf267890cc.png)

**Comment by x-calibre** [comment]
Thank you so much for pointing it out !
