### ISSUE TITLE
should a user be required to login in some form to post?

### ISSUE THREAD

**Issue by jeanconn** [x-calibre/astropython#45]
I just posted in the Education section without login and without supplying an email address, so I'm not sure how we'd contact somebody to verify content to moderate this.

**Comment by x-calibre** [comment]
@taldcroft  had earlier suggested we add this "Guest Posting" / "Anonymous User" feature ! So I added the feature specifically ! 

Guest Users are allowed to post , but not allowed to save anything. In the moderation panel and everywhere else , the "author name" will appear as "Anonymous"

Should I remove this ? @taldcroft  @jeanconn

**Comment by jeanconn** [comment]
Do we need at least an email address or do we want this to be fully
anonymous?

**Comment by x-calibre** [comment]
Adding this email feature would mean , the user shares his email, and in the backend we actually create a new user (based on his email, if he is already not registered) and store that in the "author" field.So basically that's the same as a normal user (technically)

Its more about the requirement , if an email field is required , I will add it !  

(Suggestion: Maybe add an "optional" email field. It could favor both cases)

**Comment by taldcroft** [comment]
I'm now inclined to agree with @jeanconn that to actually post material you need to authenticate. (Sometimes my opinion changes, sorry!)  But let's leave this in place for the moment and discuss with people evaluating the site to get a broader opinion.
