### ISSUE TITLE
Discuss database backup and restore in deployment / site management guide

### ISSUE THREAD

**Issue by taldcroft** [x-calibre/astropython#46]
Just in case there is a disaster...

**Comment by x-calibre** [comment]
I guess we will require a database backup script ... converts the current records to JSON file and restore back those JSON files (like we do in the population script)

**Comment by x-calibre** [comment]
@taldcroft  Running backup.py converts all our data to JSON files after which we can do a git commit and all the data will be available in our astropython repo
Running restore.py restores that data into our new server / database

**Comment by jeanconn** [comment]
Should we use backup.py from a cron task?

**Comment by x-calibre** [comment]
Thats nice ! I can add that always !
