### ISSUE TITLE
Scrub legacy content and populate with new content

### ISSUE THREAD

**Issue by taldcroft** [x-calibre/astropython#49]
- [ ] - Look for and delete posts that are irrelevant now
- [ ] - Remove tags that are not useful or outdated ("answers", "resources", "PyCon 2011")
- [ ] - Add new content, especially stuff like astropy affiliated packages

This is mostly an issue for @taldcroft but others can help out!

**Comment by hamogu** [comment]
How about packages, e.g atpy and asciitable still exist and can be installed. Should we remove them entirely out just add a warning?

**Comment by x-calibre** [comment]
We have made 3 categories - "Recommended", "Active" and "Deprecated" . Currently all the packages are unassigned. After they are properly categorized , they can be used to guide the users !

**Comment by taldcroft** [comment]
@hamogu - yes, atpy and asciitable will be Deprecated.
