### ISSUE TITLE
Include a link to an "About this site" page

### ISSUE THREAD

**Issue by taldcroft** [x-calibre/astropython#54]
It can be at the bottom and does not need to be too prominent.

**Comment by taldcroft** [comment]
This "About this site" link could have the git repo link, and should include some text saying that the site was developed by Aman Jhunjhunwala, supported by Google Summer of Code 2015 funding, with mentorship provided by the Astropy project via the Python Software Foundation.  (I'm not sure if there is a specific acknowledgement wording that is normally used).

@x-calibre - you can have a link to your contact page or information if you desire for professional reference.

**Comment by x-calibre** [comment]
@jeanconn wasn't a part of the old AstroPython site , so I didn't have her bio for the website ! It would be great if you could update that !

**Comment by jeanconn** [comment]
And I've just done some testing so I'm fine with no bio.

**Comment by x-calibre** [comment]
It would be great if you could provide some !
