### ISSUE TITLE
Colors still too light

### ISSUE THREAD

**Issue by taldcroft** [x-calibre/astropython#56]
The main yellow color used throughout, in particular for links, is way too light.  On my older monitor the color is nearly invisible.  Here is what I'm seeing:
![image](https://cloud.githubusercontent.com/assets/348089/8747521/f0c14a8e-2c61-11e5-9838-e99a9c924f99.png)

**Comment by x-calibre** [comment]
Is it better now ? @taldcroft

**Comment by x-calibre** [comment]
Need to make the color darker

**Comment by jeanconn** [comment]
I think it it still too light on my display.  Also, the light grays.  I've badly marked this in a new screenshot:
![light_colors](https://cloud.githubusercontent.com/assets/791508/8776465/4f9f66ee-2ebf-11e5-9f31-5bc8263878c4.png)
