### ISSUE TITLE
Remove recommended / others category and replace with tags

### ISSUE THREAD

**Issue by taldcroft** [x-calibre/astropython#58]
Somehow this category for packages has never *quite* made sense.  So I think a better strategy is to have three dedicated tags: `recommended` and `active` and `deprecated`.  The `deprecated` tag would be used sparingly for things like `ATPy` where we know we won't offend the developer (@astrofrog) and it really has been superseded.  There should be some text at the top highlighting the `recommended` and `active` tags as ways to get to relevant packages, e.g. "Click on the **Recommended** tag to select packages that meet our standards of code and documentation, and the **Active** tag for projects that are being actively developed and/or widely used."

Another strategy to avoid the "help text" is to have a separate sidebar element above tags which is basically like tags except it only has the two "Recommended" and "Active" tags.

**Comment by x-calibre** [comment]
Should we remove all the other tags for packages , then ? Having multiple tags makes it easier to filter results though! I could have 3 sections on the package homepage stating `active` , `recommended` and `deprecated` then

**Comment by taldcroft** [comment]
No, do not remove other tags, since I completely agree the existing tags are crucial!  I just want there to be a simple way to mark packages as recommended and/or active or deprecated.  Doing this with tags makes it more visible and easier (and allows independently choosing either one, which you couldn't do in sections). 

For now this would be an issue for the legacy content migration, since the idea would be to add a `recommended` and `active` tag to every package.  Then we can go through the database and change those as needed.

**Comment by x-calibre** [comment]
Replaced with checkboxes... worth the additional complexity !
