### ISSUE TITLE
Migrate legacy packages "Description" and "Homepage URL"

### ISSUE THREAD

**Issue by taldcroft** [x-calibre/astropython#66]
All the "Package and resources" posts have a standard header like:
```
Description: Convenience script(s) around pyraf/s-extractor to align a stack of dithered FITS images. 
Homepage URL: http://obswww.unige.ch/~tewes/alipy/
```

In the ingest process, parse out those pieces and remove them from the Body.  Put the `Description` in the `Abstract` field and the `Homepage URL` into the `Homepage URL` field.

**Comment by taldcroft** [comment]
About `Homepage URL`, right now there is no way to edit the `Homepage URL` field (except as admin).  Would that be easy to put in?  Otherwise I guess we can just use the admin panel if the URL for a package changes.

**Comment by x-calibre** [comment]
I will add the edit field soon ! After I closed the issue, I realized not all of the articles had the format 
`Description: XXX-XXX
Homepage URL: XXX-XXX ` 
Manually updating those files which do not follow the pattern

**Comment by x-calibre** [comment]
Done ! Homepage URL can be edited from the front end (a pencil like icon appears on hover, clicking which allows editing)

**Comment by taldcroft** [comment]
Sorry that we didn't follow the convention always... The fixes for this issue look great!
