### ISSUE TITLE
Consider making the view for Teach and Learn topics be list view like packages

### ISSUE THREAD

**Issue by taldcroft** [x-calibre/astropython#72]
For people just browsing for a topic in Teach and Learn, the more compact list view like in Packages will probably work better.  Interested in feedback here.

**Comment by x-calibre** [comment]
The current layout is similar to the list view(with a bit more info), but the list view feels pretty outdated and doesn't work well on smaller devices. I don't think that it is a good option !

If required , I can increase the number of posts appearing in each page !
