### ISSUE TITLE
[DISCUSS] Authentications options adequate?

### ISSUE THREAD

**Issue by taldcroft** [x-calibre/astropython#77]

**Comment by x-calibre** [comment]
I could add the following :- (if needed)
Amazon OAuth2 http://login.amazon.com/website
Angel OAuth2
AOL OpenId http://www.aol.com/
Appsfuel OAuth2
Behance OAuth2
BelgiumEIDOpenId OpenId https://www.e-contract.be/
Bitbucket OAuth1
Box OAuth2
Clef OAuth2
Coursera OAuth2
Dailymotion OAuth2
DigitalOcean OAuth2 https://developers.digitalocean.com/documentation/oauth/
Disqus OAuth2
Douban OAuth1 and OAuth2
Dropbox OAuth1 and OAuth2
Evernote OAuth1
Exacttarget OAuth2
Facebook OAuth2 and OAuth2 for Applications
Fedora OpenId http://fedoraproject.org/wiki/OpenID
Fitbit OAuth1
Flickr OAuth1
Foursquare OAuth2
Google App Engine Auth
Github OAuth2
Google OAuth1, OAuth2 and OpenId
Instagram OAuth2
Jawbone OAuth2 https://jawbone.com/up/developer/authentication
Kakao_ OAuth2 https://developer.kakao.com
Khan Academy OAuth1
Launchpad OpenId
Linkedin OAuth1
Live OAuth2
Livejournal OpenId
LoginRadius_ OAuth2 and Application Auth
Mailru OAuth2
MapMyFitness OAuth2
Mendeley OAuth1 http://mendeley.com
Mixcloud OAuth2
Moves app OAuth2 https://dev.moves-app.com/docs/authentication
Mozilla Persona
NaszaKlasa OAuth2
Odnoklassniki OAuth2 and Application Auth
OpenId
OpenStreetMap OAuth1 http://wiki.openstreetmap.org/wiki/OAuth
OpenSuse OpenId http://en.opensuse.org/openSUSE:Connect
PixelPin OAuth2
Pocket OAuth2
Podio OAuth2
Rdio OAuth1 and OAuth2
Readability OAuth1
Reddit OAuth2 https://github.com/reddit/reddit/wiki/OAuth2
Shopify OAuth2
Skyrock OAuth1
Soundcloud OAuth2
Stackoverflow OAuth2
Steam OpenId
Stocktwits OAuth2
Strava OAuth2
Stripe OAuth2
Taobao OAuth2 http://open.taobao.com/doc/detail.htm?id=118
ThisIsMyJam OAuth1 https://www.thisismyjam.com/developers/authentication
Trello OAuth1 https://trello.com/docs/gettingstarted/oauth.html
Tripit OAuth1
Tumblr OAuth1
Twilio Auth
Twitter OAuth1
VK.com OpenAPI, OAuth2 and OAuth2 for Applications
Weibo OAuth2
Withings_ OAuth1
Wunderlist OAuth2
Xing OAuth1
Yahoo OpenId and OAuth2
Yammer OAuth2
Yandex OAuth1, OAuth2 and OpenId
Zotero OAuth1

**Comment by hamogu** [comment]
I'm locked into the store with github, but I cannot post a comment on a package, because that requires a separate login with d f t g. I've seen the f g t logos bit over never heard of disqus. It would be great if living b into the site would at the same time allow me to comment instead I if having two separate logins on the same page.

**Comment by x-calibre** [comment]
Opened an issue for the same ... It will be resolved soon....Thank you @hamogu !
