### ISSUE TITLE
[DISCUSS] General site organization and navigation

### ISSUE THREAD

**Issue by taldcroft** [x-calibre/astropython#78]

**Comment by Gabriel-p** [comment]
I believe 'Latest posts' should be *above* the 'New to Python?' block.

Also, the text is too wide, it makes it very hard to read the description of a package when one has to move it eyes almost the entire width of the screen.

**Comment by x-calibre** [comment]
Thanks for the suggestion ! Will shift the "New to Python?" down and get the latest posts up in some compact tabular fashion.

**Comment by x-calibre** [comment]
@Gabriel-p  We have added "more content" to the homepage(arranged in small bloacks) and also shifted "New to Python?" block towards the bottom ...Thank you for the suggestion !
