### ISSUE TITLE
[DISCUSS] Ease of finding information

### ISSUE THREAD

**Issue by taldcroft** [x-calibre/astropython#79]

**Comment by bsipocz** [comment]
It seems like that most of the astropy affiliated packages are missing from the "packages" list while potentially obsolete ones are listed. But even if they were listed, the list is a bit too long. So I wonder whether any plans to structurize/clusterize it somehow beyond the current filters and tags.

**Comment by taldcroft** [comment]
@bsipocz - I almost wrote in the email, (and probably should have), that the actual content and lists of packages still needs a lot of work.  So definitely astropy affil packages will be there.  Maybe they would have an `astropy` tag, which is conveniently near the top of any alphabetical tag list.  See #49, which I just edited to include adding new stuff.
