### ISSUE TITLE
[DISCUSS] Accessibility

### ISSUE THREAD

**Issue by taldcroft** [x-calibre/astropython#81]

**Comment by jeanconn** [comment]
I don't know if anybody uses it anymore, but it looks like WAVE 

http://wave.webaim.org/report#/amanjhunjhunwala.pythonanywhere.com

on the main page has the red warnings on lack of labels on the login links and on the form fields.

**Comment by x-calibre** [comment]
WAVE is quite outdated because it doesn't encourage newer design patterns and is sort -of old school (Eg. It shows errors on the feedback form because there are no explicit labels - PLEASE ENTER YOUR EMAIL HERE ! But of a user sees the form , I am pretty sure he will figure everything out )

**Comment by jeanconn** [comment]
For this accessibility discussion, the question is not just "if a user sees
the form" the question is also "if a screen reader reads the form".

To start, I don't see where adding alt text to the facebook, google, and
github login links would be inconsistent with modern design.

And for the form, hidden labels or ARIA properties are an option if, say
"Name:" before the input box, is not consistent with the design, right?

**Comment by x-calibre** [comment]
I will read WAVE's data and take care of as many errors as I can in a few days ! :)

**Comment by jeanconn** [comment]
I think the very few red items it flags are probably valuable (link alt
text, form labels),  but I do not doubt that there are better/more modern
checkers out there and evolving standards.

Part of this discussion should probably be figuring out if there is a good
recommended one at this time.

**Comment by jeanconn** [comment]
I think keyboard navigation is currently non-functional, but that may
be beyond the present scope.

**Comment by x-calibre** [comment]
I have tested the website on a variety of testers and have been working to increase the speed , here are some screen shots (Before is before optimizing, After is after performing optimizations)
Test 1 : GTMetrix
Before:
![image](https://cloud.githubusercontent.com/assets/10886527/8889834/3f6824c6-3308-11e5-97ec-12d91c34f8df.png)
After :
![image](https://cloud.githubusercontent.com/assets/10886527/8889838/815101c8-3308-11e5-8598-05369adf50e4.png)
 (I am adding 3 of them here, because there are no sharing links! )

**Comment by x-calibre** [comment]
The speed of the website is slow primarily because of Trinket, FB and Twitter embedd---remove them and the site loads quite quick! 
Could look into server and browser based caching for better performance

**Comment by jeanconn** [comment]
Not sure if the performance metrics and discussion should be in its own issue?  I agreed with @Gabriel-p that I didn't think it was that heavy.

**Comment by x-calibre** [comment]
I will move them to a separate issue and delete the comments...

**Comment by jeanconn** [comment]
I'd leave the #88  open a bit longer (and see if you hear back from everybody who raised it).

**Comment by x-calibre** [comment]
WAVE now gives 0 errors.... lots of manual corrections done
