### ISSUE TITLE
Better font and constrast

### ISSUE THREAD

**Issue by x-calibre** [x-calibre/astropython#88]

**Comment by bernie-simon** [comment]
One mistake I see 20 something web designers making all the time is using low contrast colors in a small font size. Not everyone has good eyesight and what might be easily legible to you will be hard for others to read. The font color should be darker and the size increased,.

**Comment by x-calibre** [comment]
@bernie-simon  Thank you for taking the time out for the feedback ! We will definitely improve the font and add a bit more contrast !

**Comment by Gabriel-p** [comment]
Was just about to open anew issue about the contrast.

A slim grayish font over a white background might not be the best choice.

**Comment by x-calibre** [comment]
We definitely took a huge risk choosing an unconventional yellow-white template.We will surely rectify the contrast issues and even the fonts, so that everyone is happy with it !

**Comment by x-calibre** [comment]
@Gabriel-p @bernie-simon , We have listened and implemented a lot of changes for contrast and fonts ! Please give the web app a try again , hopefully you will not be disappointed !

**Comment by Gabriel-p** [comment]
The contrast is much better now, thanks!
