### ISSUE TITLE
Site Performance Metrics

### ISSUE THREAD

**Issue by x-calibre** [x-calibre/astropython#90]
Consider removing Trinket, Twitter, Facebook or animations for faster loading?
Could implement server/browser based caching (possible side-effect : CSS changes,etc take time to update)

**Comment by x-calibre** [comment]
I have tested the website on a variety of testers and have been working to increase the speed , here are some screen shots (Before is before optimizing, After is after performing optimizations)
Test 1 : GTMetrix https://gtmetrix.com
Before:
![image](https://cloud.githubusercontent.com/assets/10886527/8889834/3f6824c6-3308-11e5-97ec-12d91c34f8df.png)
After :
![image](https://cloud.githubusercontent.com/assets/10886527/8889838/815101c8-3308-11e5-8598-05369adf50e4.png)
 (I am adding 3 of them here, because there are no sharing links! )

Test 2 : Google Page Insights 
Before
![image](https://cloud.githubusercontent.com/assets/10886527/8889885/686b77f4-330a-11e5-869d-bb140f90ab15.png)
![image](https://cloud.githubusercontent.com/assets/10886527/8889887/79911dc2-330a-11e5-809e-610da61a56a6.png)

Test 4: Browser Stack https://www.browserstack.com/ : For testing across all browsers and OS All the tests passed (without Trinket added)

**Comment by Gabriel-p** [comment]
The page load time could definitely use some improvement.

I believe the goal should be <2 sec so the page doesn't feel sluggish.

**Comment by x-calibre** [comment]
Working on it , hopefully in 3-4 days, I will get some server side and browser side caching up, after which , the only options left would be to let go of some of the plugins (Page Load Affecting Time : Trinket>>Facebook>>>>Twiter)

**Comment by x-calibre** [comment]
Few Stats -
After removing all animations,Trinket,Twitter and FB links -
![image](https://cloud.githubusercontent.com/assets/10886527/8977430/b94b62c4-36b6-11e5-804c-22f1d5adce68.png)

**Comment by x-calibre** [comment]
After modifying our Homepage for faster load times and implementing a few Cache mechanisms :-
![image](https://cloud.githubusercontent.com/assets/10886527/8989720/90178b6c-370b-11e5-98c2-407b59b0735a.png)

I will betrying more cache based speedup techniques

**Comment by Gabriel-p** [comment]
It definitely feels much faster now, good job!
