### ISSUE TITLE
Simple reformatting issue

### ISSUE THREAD

**Issue by ycopin** [x-calibre/astropython#91]
When reformatting the package description (eg. http://amanjhunjhunwala.pythonanywhere.com/packages/poppy97/) for the "Latest posts" section of http://amanjhunjhunwala.pythonanywhere.com/, the newlines are just removed while they should be replaced by space. E.g. 

"""
POPPY (Physical Optics Propagation in PYthon) simulates physical
optical propagation including diffraction. It implements a
flexible framework for modeling Fraunhofer (far-field)
[...]
"""

is converted to

"""
POPPY (Physical Optics Propagation in PYthon) simulates physicaloptical propagation including diffraction. It implements aflexible framework for modeling Fraunhofer (far-field)...
"""

Note the missing spaces in "physicaloptical" and "aflexible".

**Comment by x-calibre** [comment]
Thank you for taking the time out for the feedback ! 
At first glance , this looks like a legacy data problem (from the old astropython, which was all html formatted) . Will investigate it further !

**Comment by x-calibre** [comment]
Created separate combined issue to handle the same
