### ISSUE TITLE
Number of comments incorrect

### ISSUE THREAD

**Issue by cdeil** [x-calibre/astropython#96]
The number of comments on the page is incorrect (shows 0, is 1):

<img width="1201" alt="screen shot 2015-08-02 at 17 46 54" src="https://cloud.githubusercontent.com/assets/852409/9026830/82519b8c-393e-11e5-9946-6fe37eea1307.png">

Maybe can't be avoided, maybe a separate issue: if I'm logged in to the site with Google, why do I have to log in again to comment?

**Comment by x-calibre** [comment]
The number of comments take a bit of time to update (because those are handled by a third party client) .... Issue #87 deals with the separate logins for site and comments. It will be rectified quite soon !
