### ISSUE TITLE
Separate search field on packages page?

### ISSUE THREAD

**Issue by cdeil** [x-calibre/astropython#97]
On the packages page I wanted to filter the list by entering a search keyword:
http://amanjhunjhunwala.pythonanywhere.com/packages/

Took me 20 seconds to figure out I have to go via the general search with the magnifying glass in the top right corner.

Maybe an extra field to filter the list directly above, well visible on the page would be a good idea?

**Comment by taldcroft** [comment]
I think it would be good to have a Search box at the top of the right column (above "Sort by") where you can just type and it is searching on whatever category you are currently viewing (e.g. All packages, or Tutorials, etc).

**Comment by x-calibre** [comment]
Will add it soon !

**Comment by x-calibre** [comment]
Added !
